apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab23
  name: backend-lab23
  labels:
    app: backend-lab23
spec:
  selector:
    matchLabels:
      app: backend-lab23
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-lab23
    spec:
      containers:
        - name: backend-lab23
          image: maxhyeon/backend-lab23:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_CONNECTION
              value: 169.56.75.43:31482
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: passw0rd